-------------------------------new-----------------------------------------------

CREATE TABLE Calificaciones(
	CI_ESTUDIANTE number PRIMARY KEY,
	ANIO number,
  	semestre number,
	LICENCIATURA varchar(500),
	CODIGO number,
	MATERIA varchar(500),
	TIPO_MATERIA varchar(500),
	DOCENTE_NOMBRE varchar(500),
	DOCENTE_APELLIDO varchar(500),
	NOMBRE_ESTUDIANTE varchar(500),
	APELLIDO_ESTUDIANTE varchar(500),
	CALIFICACION NUMBER
);


CREATE TABLE DOCENTE(
    CI NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(500),
	APELLIDO VARCHAR(500),
	RIF VARCHAR(500),
	CORREO VARCHAR(500),
	FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATE,
	DIRECCION VARCHAR(500),
	ESTADO_CIVIL VARCHAR(500),
	SEXO VARCHAR(500),
	TIPO_DOCENTE VARCHAR(500)
);


CREATE TABLE ESTUDIANTE(
	CI NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(500),
	APELLIDO VARCHAR(500),
	CORREO VARCHAR(500),
	DIRECCION VARCHAR(500),
	FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATE,
	SEXO VARCHAR(510)
);

CREATE TABLE LICENCIATURA(
	ID_LICENCIATURA NUMBER PRIMARY KEY,
	DESCRIPCION VARCHAR(510)
);

CREATE TABLE SECCION(
	ID_SECCION NUMBER PRIMARY KEY,
	DESCRIPCION VARCHAR(500)
);

CREATE TABLE SEMESTRE(
	ID_SEMESTRE NUMBER PRIMARY KEY,
	ANIO NUMBER,
	SEMESTRE NUMBER
);

CREATE TABLE MATERIA(
	COD_MATERIA NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(500),
	ID_LICENCIATURA NUMBER,
	TIPO_MATERIA varchar(500),
	creditos NUMBER,
	CONSTRAINT LIC_FK FOREIGN KEY(ID_LICENCIATURA) REFERENCES LICENCIATURA(ID_LICENCIATURA)
);


CREATE TABLE inscribe(
  CI_DOCENTE number,
  ID_SECCION number,
  ID_SEMESTRE number,
  COD_MATERIA number,
  CI_ESTUDIANTE number,
  CONSTRAINT DOC_FK FOREIGN KEY(CI_DOCENTE) REFERENCES DOCENTE(CI),
  CONSTRAINT SEC_FK FOREIGN KEY(ID_SECCION) REFERENCES SECCION(ID_SECCION),
  CONSTRAINT SEM_FK FOREIGN KEY(ID_SEMESTRE) REFERENCES SEMESTRE(ID_SEMESTRE),
  CONSTRAINT MAT_FK FOREIGN KEY(COD_MATERIA) REFERENCES MATERIA (COD_MATERIA),
  CONSTRAINT EST_FK FOREIGN KEY(CI_ESTUDIANTE) REFERENCES ESTUDIANTE (CI),
  CONSTRAINT INSC_PK PRIMARY KEY (CI_DOCENTE, ID_SECCION, ID_SEMESTRE, COD_MATERIA, CI_ESTUDIANTE)
);
  


CREATE TABLE CURSA(
	CI_ESTUDIANTE NUMBER,
	ID_LICENCIATURA NUMBER,
	FECHA_INGRESO DATE,
	CONSTRAINT ESTUD_FK FOREIGN KEY(CI_ESTUDIANTE) REFERENCES ESTUDIANTE(CI),
	CONSTRAINT LICEN_FK FOREIGN KEY(ID_LICENCIATURA) REFERENCES LICENCIATURA(ID_LICENCIATURA),
	CONSTRAINT CURSA_PK PRIMARY KEY (CI_ESTUDIANTE, ID_LICENCIATURA)
);

CREATE TABLE semestre_materia(
  id_semestre number,
  cod_materia number,
  CONSTRAINT S_FK FOREIGN KEY(ID_SEMESTRE) REFERENCES SEMESTRE(ID_SEMESTRE),
  CONSTRAINT M_FK FOREIGN KEY(COD_MATERIA) REFERENCES MATERIA(COD_MATERIA),
  constraint SMPK primary key (id_semestre, cod_materia)
);

CREATE TABLE programa_materia(
  id_programa_item number primary key,
  id_semestre NUMBER,
  cod_materia number,
  fecha date,
  semana number,
  clase number,
  tema varchar (510),
  descripcion varchar(510),
  CONSTRAINT SEMESTRE_MAT_FK FOREIGN KEY(ID_SEMESTRE, COD_MATERIA) REFERENCES SEMESTRE_MATERIA(ID_SEMESTRE, COD_MATERIA)
);

create table asistencia(
  id_asistencia number,
  id_programa_item number,
  CI_DOCENTE number,
  ID_SECCION number,
  ID_SEMESTRE number,
  COD_MATERIA number,
  CI_ESTUDIANTE number,
  asistio number,
  CONSTRAINT INSC_FK FOREIGN KEY(CI_DOCENTE, ID_SECCION, ID_SEMESTRE, COD_MATERIA, CI_ESTUDIANTE) REFERENCES INSCRIBE(CI_DOCENTE, ID_SECCION, ID_SEMESTRE, COD_MATERIA, CI_ESTUDIANTE),
  CONSTRAINT PROGRAMA_ITEM_FK FOREIGN KEY (ID_PROGRAMA_ITEM) REFERENCES PROGRAMA_MATERIA(ID_PROGRAMA_ITEM) 
);

--------------------------------------------------------------------------------------
