CREATE TABLE DIM_ESTUDIANTE(
	ID_DIM_ESTUDIANTE NUMBER PRIMARY KEY,
	CI NUMBER,
	NOMBRE VARCHAR(510),
	APELLIDO VARCHAR(510),
	CORREO VARCHAR(510),
	DIRECCION VARCHAR(510),
	FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATE,
	SEXO VARCHAR(510)
);

CREATE TABLE DIM_LICENCIATURA(
	ID_DIM_LICENCIATURA NUMBER PRIMARY KEY,
	ID_LICENCIATURA NUMBER,
	DESCRIPCION VARCHAR(510)
);

CREATE TABLE DIM_PROGRAMA_MATERIA(
	ID_DIM_PROGRAMA_MATERIA NUMBER PRIMARY KEY,
	ID_PROGRAMA_ITEM NUMBER,
	ID_SEMESTRE NUMBER,
	COD_MATERIA NUMBER,
	FECHA DATE,
	SEMANA NUMBER,
	CLASE NUMBER,
	TEMA VARCHAR (510),
	DESCRIPCION VARCHAR(510)
);

CREATE TABLE DIM_MATERIA(
	ID_DIM_MATERIA NUMBER PRIMARY KEY,
	COD_MATERIA NUMBER,
	NOMBRE VARCHAR (510),
	TIPO_MATERIA VARCHAR(510),
	CREDITOS NUMBER
);

CREATE TABLE DIM_SECCION(
	ID_DIM_SECCION NUMBER PRIMARY KEY,
	ID_SECCION NUMBER,
	DESCRIPCION VARCHAR(500)
);

CREATE TABLE DIM_DOCENTE
(
	ID_DIM_DOCENTE NUMBER PRIMARY KEY,
    CI NUMBER,
	NOMBRE VARCHAR(500),
	APELLIDO VARCHAR(500),
	RIF VARCHAR(500),
	CORREO VARCHAR(500),
	FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATE,
	DIRECCION VARCHAR(500),
	ESTADO_CIVIL VARCHAR(500),
	SEXO VARCHAR(500),
	TIPO_DOCENTE VARCHAR(500)	
);

CREATE TABLE DIM_TIEMPO(
	ID_DIM_TIEMPO NUMBER PRIMARY KEY,
	COD_ANIO NUMBER,
	DESC_ANIO VARCHAR(500),
	COD_SEMESTRE NUMBER,
	DESC_SEMESTRE VARCHAR(500),
	COD_MES NUMBER,
	DESC_MES VARCHAR(500),
	COD_DIA NUMBER,
	DESC_DIA VARCHAR(500),
	FECHA_COMPLETA DATE
);

-----------------FACT--------------------------------------------------------------------

CREATE TABLE REGISTRO_ACADEMICO_FT(
	ID_DIM_TIEMPO NUMBER,
	ID_DIM_ESTUDIANTE NUMBER,
	ID_DIM_LICENCIATURA NUMBER,
	EFICIENCIA NUMBER,
	PROMEDIO_APROBADAS NUMBER,
	PROMEDIO_GENERAL NUMBER,
	PROMEDIO_PONDERADO NUMBER,
	UC_INSCRITAS NUMBER,
	UC_APROBADAS NUMBER,
	UC_RETIRADAS NUMBER,	
	CONSTRAINT FKT_DIM_TIEMPO FOREIGN KEY (ID_DIM_TIEMPO) REFERENCES DIM_TIEMPO(ID_DIM_TIEMPO) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_ESTUDIANTE FOREIGN KEY (ID_DIM_ESTUDIANTE) REFERENCES DIM_ESTUDIANTE(ID_DIM_ESTUDIANTE) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_LICENCIATURA FOREIGN KEY (ID_DIM_LICENCIATURA) REFERENCES DIM_LICENCIATURA(ID_DIM_LICENCIATURA) ON DELETE CASCADE,	
	CONSTRAINT PKT_REGISTRO_ACADEMICO_FT PRIMARY KEY(ID_DIM_TIEMPO, ID_DIM_ESTUDIANTE, ID_DIM_LICENCIATURA)
);

CREATE TABLE REGISTRO_MATERIA_FT(
	ID_DIM_TIEMPO NUMBER,
	ID_DIM_ESTUDIANTE NUMBER,
	ID_DIM_LICENCIATURA NUMBER,
	ID_DIM_MATERIA NUMBER,
	ID_DIM_SECCION NUMBER,
	ID_DIM_DOCENTE NUMBER,
	NOTA NUMBER,
	ESTADO VARCHAR(510),
	CONSTRAINT FKT_DIM_TIEMPO3 FOREIGN KEY (ID_DIM_TIEMPO) REFERENCES DIM_TIEMPO(ID_DIM_TIEMPO) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_ESTUDIANTE3 FOREIGN KEY (ID_DIM_ESTUDIANTE) REFERENCES DIM_ESTUDIANTE(ID_DIM_ESTUDIANTE) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_MATERIA2 FOREIGN KEY (ID_DIM_MATERIA) REFERENCES DIM_MATERIA(ID_DIM_MATERIA) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_SECCION2 FOREIGN KEY (ID_DIM_SECCION) REFERENCES DIM_SECCION(ID_DIM_SECCION) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_LICENCIATURA2 FOREIGN KEY (ID_DIM_LICENCIATURA) REFERENCES DIM_LICENCIATURA(ID_DIM_LICENCIATURA) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_DOCENTE FOREIGN KEY (ID_DIM_DOCENTE) REFERENCES DIM_DOCENTE(ID_DIM_DOCENTE) ON DELETE CASCADE,
	CONSTRAINT PKT_REGISTRO_MATERIA_FT PRIMARY KEY(ID_DIM_TIEMPO, ID_DIM_ESTUDIANTE, ID_DIM_MATERIA, ID_DIM_SECCION, ID_DIM_LICENCIATURA, ID_DIM_DOCENTE)

);
CREATE TABLE ASISTENCIA_FT(
	ID_DIM_TIEMPO NUMBER,
	ID_DIM_ESTUDIANTE NUMBER,
	ID_DIM_MATERIA NUMBER,
	ID_DIM_SECCION NUMBER,
	ID_DIM_PROGRAMA_MATERIA NUMBER,
	ASISTIO NUMBER,
	CONSTRAINT FKT_DIM_TIEMPO2 FOREIGN KEY (ID_DIM_TIEMPO) REFERENCES DIM_TIEMPO(ID_DIM_TIEMPO) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_ESTUDIANTE2 FOREIGN KEY (ID_DIM_ESTUDIANTE) REFERENCES DIM_ESTUDIANTE(ID_DIM_ESTUDIANTE) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_MATERIA FOREIGN KEY (ID_DIM_MATERIA) REFERENCES DIM_MATERIA(ID_DIM_MATERIA) ON DELETE CASCADE,
	CONSTRAINT FKT_DIM_SECCION FOREIGN KEY (ID_DIM_SECCION) REFERENCES DIM_SECCION(ID_DIM_SECCION) ON DELETE CASCADE,
	CONSTRAINT FKT_PROGRAMA_MATERIA FOREIGN KEY (ID_DIM_PROGRAMA_MATERIA) REFERENCES DIM_PROGRAMA_MATERIA(ID_DIM_PROGRAMA_MATERIA) ON DELETE CASCADE,
	CONSTRAINT PKT_ASISTENCIA_FT PRIMARY KEY(ID_DIM_TIEMPO, ID_DIM_ESTUDIANTE, ID_DIM_MATERIA, ID_DIM_SECCION, ID_DIM_PROGRAMA_MATERIA)

);